# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_description',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='short_description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='signature',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
